
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi]
        args: [--fix]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.46.0
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false
        additional_dependencies:
          - cryptography>=45.0.6
          - multiformats>=0.3.1.post4
          - pydantic>=2.12.5
          - pyld[aiohttp,requests]>=2.0.4
          - typing-extensions>=4.15.0
          
          # dev dependencies
          - git-cliff>=2.10.0
          - mkdocstrings-python>=2.0.1
          - pyrefly>=0.46.0
          - pytest>=8.4.1
          - pytest-cov>=7.0.0
          - zensical>=0.0.13