import datetime
import typing

from pydantic import AnyUrl

a = {
    "subject": (str | typing.List[str] | None, None),
    "relationship": (str | typing.List[str] | None, None),
    "actor": (str | typing.List[str] | None, None),
    "attachment": (str | typing.List[str] | None, None),
    "bcc": (str | typing.List[str] | None, None),
    "bto": (str | typing.List[str] | None, None),
    "cc": (str | typing.List[str] | None, None),
    "context": (str | typing.List[str] | None, None),
    "current": (str | typing.List[str] | None, None),
    "first": (str | typing.List[str] | None, None),
    "generator": (str | typing.List[str] | None, None),
    "icon": (str | typing.List[str] | None, None),
    "image": (str | typing.List[str] | None, None),
    "items": (str | typing.List[str] | None, None),
    "instrument": (str | typing.List[str] | None, None),
    "last": (str | typing.List[str] | None, None),
    "location": (str | typing.List[str] | None, None),
    "next": (str | typing.List[str] | None, None),
    "object": (str | typing.List[str] | None, None),
    "closed": (datetime.datetime | typing.List[datetime.datetime] | None, None),
    "origin": (str | typing.List[str] | None, None),
    "accuracy": (float | typing.List[float] | None, None),
    "prev": (str | typing.List[str] | None, None),
    "preview": (str | typing.List[str] | None, None),
    "replies": (str | typing.List[str] | None, None),
    "result": (str | typing.List[str] | None, None),
    "audience": (str | typing.List[str] | None, None),
    "tag": (str | typing.List[str] | None, None),
    "target": (str | typing.List[str] | None, None),
    "to": (str | typing.List[str] | None, None),
    "url": (str | typing.List[str] | None, None),
    "altitude": (float | typing.List[float] | None, None),
    "duration": (str | typing.List[str] | None, None),
    "height": (int | typing.List[int] | None, None),
    "href": (str | typing.List[str] | None, None),
    "latitude": (float | typing.List[float] | None, None),
    "longitude": (float | typing.List[float] | None, None),
    "published": (
        datetime.datetime | typing.List[datetime.datetime] | None,
        None,
    ),
    "radius": (float | typing.List[float] | None, None),
    "updated": (
        datetime.datetime | typing.List[datetime.datetime] | None,
        None,
    ),
    "width": (int | typing.List[int] | None, None),
    "describes": (str | typing.List[str] | None, None),
    "deleted": (
        datetime.datetime | typing.List[datetime.datetime] | None,
        None,
    ),
    "inbox": (str | typing.List[str] | None, None),
    "outbox": (str | typing.List[str] | None, None),
    "following": (str | typing.List[str] | None, None),
    "followers": (str | typing.List[str] | None, None),
    "streams": (str | typing.List[str] | None, None),
    "endpoints": (str | typing.List[str] | None, None),
    "liked": (str | typing.List[str] | None, None),
    "likes": (str | typing.List[str] | None, None),
    "shares": (str | typing.List[str] | None, None),
}
