[project]
name = "apmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AmaseCocoa", email = "cocoa@amase.cc" }
]
requires-python = ">=3.10"
dependencies = [
    "niquests[http3]>=3.18.2",
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "hatch>=1.16.5",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
]

[build-system]
requires = ["hatchling", "jinja2", "pyyaml", "niquests[http3]", "ruff"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/apmodel"
]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "scripts/compile.py"
