[project]
name = "apmodel"
version = "0.4.0"
description = "ActivityStreams 2.0 and nodeinfo 2.0/2.1 implementation for Python."
readme = "README.md"
authors = [
    { name = "AmaseCocoa", email = "cocoa@amase.cc" }
]
requires-python = ">=3.10"
dependencies = [
    "cryptography>=45.0.6",
    "multiformats>=0.3.1.post4",
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

[project.urls]
#Homepage = "https://ap.amase.cc"
#Documentation = ""
Repository = "https://github.com/fedi-libs/apmodel"
Issues = "https://github.com/fedi-libs/apmodel/issues"
Changelog = "https://github.com/fedi-libs/apmodel/blob/main/CHANGELOG.md"

[project.scripts]
apmodel = "apmodel:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
