# yaml-language-server: $schema=./schema.json
imports:

classes:
  PropertyValue:
    extends: null
    isCoreType: false
    as2Uri: "http://schema.org#PropertyValue"
    description: ""
    properties:
      name: 
         type: str | None
      value: 
         type: str | None